.PHONY: install run all

all: install

install:
	@echo "Installing dependencies..."
	@npm install

run:
	@echo "\n\n\nRunning the application..."
	@node stockholm.js

decrypt:
	@echo "Decrypting the application..."
	@node stockholm.js -r