# syntax=docker/dockerfile:1
FROM debian:buster

RUN apt-get update && \
    apt-get install -y vsftpd net-tools && \
    mkdir -p /var/run/vsftpd/empty && \
    useradd -m user && \
    echo "user:user" | chpasswd

COPY vsftpd.conf /etc/vsftpd.conf
COPY serverFile.txt /home/user/
COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh

EXPOSE 20 21

ENTRYPOINT [ "/entrypoint.sh" ]
CMD ["vsftpd", "/etc/vsftpd.conf"]
