# syntax=docker/dockerfile:1
FROM debian:buster

RUN apt-get update && \
    apt-get install -y vsftpd net-tools && \
    mkdir -p /var/run/vsftpd/empty && \
    useradd -m user && \
    echo "user:user" | chpasswd

COPY vsftpd.conf /etc/vsftpd.conf
COPY serverFile.txt /home/user/

EXPOSE 20 21

CMD ["vsftpd", "/etc/vsftpd.conf"]
