all: install

install:
	@echo "Installing dependencies..."
	@npm install
	@echo "\n\n\nRunning the application..."
	tsc vaccine.ts
	@echo "use 'node vaccine.js' to run the application"

.PHONY: install run all