version: "3"

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  postgres:
    build: ./postgres
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/16/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    restart: always
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  express:
    build: ./back/
    ports:
      - 3000:3000
    volumes:
      - ./back:/app
    depends_on:
      - mysql-db
      - postgres

  adminer-mysql:
    build: ./adminer/
    environment:
      ADMINER_DEFAULT_SERVER: mysql-db
      ADMINER_DEFAULT_DB: testdb
      ADMINER_DEFAULT_USER: user
      ADMINER_DEFAULT_PASS: userpassword
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - mysql-db
        # condition: service_healthy

  adminer-postgres:
    build: ./adminer/
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_DB: testdb
      ADMINER_DEFAULT_USER: postgres
      ADMINER_DEFAULT_PASS: postgres
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
  mysql_data:
