# syntax=docker/dockerfile:1
FROM debian:buster

RUN apt-get update && apt-get install -y ftp g++ libpcap-dev libcurl4-openssl-dev vim

COPY client.cpp home/
COPY clientFile.txt home/

WORKDIR /home
RUN g++ client.cpp -lcurl -o client

CMD ["tail", "-f", "/dev/null"]

# CMD ["./client"]