# syntax=docker/dockerfile:1
FROM debian:buster

RUN apt-get update && apt-get install -y ftp g++ libpcap-dev libcurl4-openssl-dev vim net-tools

COPY clientFile.txt home/
COPY src/* home/

WORKDIR /home
RUN g++ client.cpp -lcurl -o client
RUN g++ sendFile.cpp -lcurl -o send
RUN g++ receiveFile.cpp -lcurl -o receive

CMD ["tail", "-f", "/dev/null"]

# CMD ["./client"]